name: New Go CI workflow

on: [push, pull_request]

jobs:
    lint:
        name: Lint files
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go-version: [ '1.21.x' ]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: ${{matrix.go-version}}
            - name: Install golangci-lint
              run: |
                  VERSION= latest
                  DOWNLOAD_URL="https://github.com/golangci/golangci-lint/releases/download/${VERSION}/golangci-lint-${VERSION}-linux-amd64.tar.gz"
                  curl -sSfL $DOWNLOAD_URL -o golangci-lint.tar.gz
                  tar -xvzf golangci-lint.tar.gz
                  sudo mv golangci-lint-*-linux-amd64/golangci-lint /usr/local/bin/
                  golangci-lint --version
            - name: Run golangci-lint
              run: golangci-lint run

    test:
        name: Testing
        runs-on: ubuntu-latest
        needs: lint
        strategy:
            matrix:
                go-version: [ '1.21.x' ]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: ${{matrix.go-version}}
            - name: Run unit test
              run: go test -v -cover -coverprofile=coverage.out ./.. > result.log
            - name: Uploading Test Result Log
              uses: actions/upload-artifact@v3
              with:
                name: Test Result
                path: result.log

    build:
        name: Building
        runs-on: ubuntu-latest
        needs: test
        strategy:
            matrix:
                go-version: [ '1.21.x' ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: ${{matrix.go-version}}
            - name: Bulid Go
              run: go build -v ./..