name: New Go CI workflow

on: [push, pull_request]

jobs:
    lint:
        name: Lint files
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go-version: [ '1.21.x' ]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: ${{matrix.go-version}}
            - name: Linting 
              uses: golangci/golangci-lint-action@v3
              with:
                version: latest

    test:
        name: Testing
        runs-on: ubuntu-latest
        needs: lint
        strategy:
            matrix:
                go-version: [ '1.21.x' ]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: ${{matrix.go-version}}
            - name: Run unit test
              run: go test -v -cover -coverprofile=coverage.out ./.. > result.log
            - name: Uploading Test Result Log
              uses: actions/upload-artifact@v3
              with:
                name: Test Result
                path: result.log

    build:
        name: Building
        runs-on: ubuntu-latest
        needs: test
        strategy:
            matrix:
                go-version: [ '1.21.x' ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: ${{matrix.go-version}}
            - name: Bulid Go
              run: go build -v ./..