name: New Go CI workflow

on: [push, pull_request]

jobs:
    test:
        name: Testing
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [ '1.21.x' ]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: ${{matrix.go-version}}
            - name: Install dependencies
              run: go mod tidy
            - name: Run unit test
              run: go test -v ./...
            - name: Uploading Test Result Log
              uses: actions/upload-artifact@v3
              with:
                name: Test Result
                path: result.log

    build:
        name: Building
        runs-on: ubuntu-latest
        needs: test
        strategy:
            matrix:
                go-version: [ '1.21.x' ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: ${{matrix.go-version}}
            - name: Install dependencies
              run: go mod tidy
            - name: Bulid Go
              run: go build -v ./..