name: Go CI workflow

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go-version: [ '1.19', '1.20', '1.21.x' ]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: ${{matrix.go-version}}
            - name: Install dependencies
              run: go install example.com/cmd@latest
            - name: Build Go
              run: go build -v ./...
            - name: Test with Go
              run: go test -json > TestResults-${{ matrix.go-version }}.json
            - name: Uploading the test results
              uses: actions/upload-artifact@v3
              with:
                name: Go-results-${{ matrix.go-version }}
                path: TestResults-${{ matrix.go-version }}.json